routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return redirect()->to('https://my.gov.uz/');
////    return view('welcome');
////    return redirect()->route('login');
//});

Route::middleware(['auth'])->group(function () {

    Route::get('index', function (){
        return view('index');
    })->name('home.index');

    ///// Super admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'super_admin'], function (){

        Route::resources([
            'admin'=>\App\Http\Controllers\AdminController::class]);

    });

    ///// Admin routes /////
    Route::group(['prefix'=>'admin','middleware'=>'admin'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'index', 'show','edit','update'
        ]);

    });

    ///// Manager routes /////
    Route::group(['prefix'=>'admin','middleware'=>'manager'], function (){

        Route::resource('admin', \App\Http\Controllers\AdminController::class)->only([
            'show','edit','index'
        ]);

        Route::resource('buyer', \App\Http\Controllers\BuyerController::class)->only([
            'index'
        ]);
    });

    Route::resource('client',\App\Http\Controllers\ClientController::class);
    Route::resource('mehnat',\App\Http\Controllers\MehnatController::class);
    Route::resource('band_qilish',\App\Http\Controllers\BandQilishController::class);


});


Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('',function (Request $request){



    if ($request->number && $request->date && $request['g-recaptcha-response']){
        $client = \App\Models\Client::where('doc_number','=',$request->number)
            ->where('doc_date','=',$request->date)
            ->first();

    }else{
        $client = false;
    }

//    dd($client);


    return view('mehnat.index',compact('client'));
})->name('get.client');


//Route::get('check',function (){
//
//    return url('https://my.mehnat.uz');
//});
//
//Route::post('find-client',function (Request $request){
//
//    return redirect()->route('get.client',$request->doc_number);
//
//})->name('find.client');

resources/views/admin/edit.blade.php
@extends('layouts.main')
@section('main-content')
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Admin tahrirlash</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('admin.update', Auth::user()->id) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="card-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Ism</label>
                    <input name="name" type="text" class="form-control" value="{{ $admin->name }}" id="exampleInputEmail1" placeholder="Ism kiriting">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input name="email" type="email" class="form-control" value="{{ $admin->email }}" id="exampleInputEmail1" placeholder="Email kiriting">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Parol</label>
                    <input name="password" type="text" class="form-control" id="exampleInputPassword1" placeholder="Yangi parol" required>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="exampleInputFile">File rasm</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input name="image" id="imgInp" onchange="preview(frame)" type="file" class="custom-file-input" id="exampleInputFile">
                                    <label class="custom-file-label" for="exampleInputFile">Tanlang</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">Yuklash</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <label class="mb-2" for="rasm"><b>Rasm</b></label>
                        <img id="frame" class="ml-2" src="{{asset('public/storage/images/'.$admin->image)}}" width="100px" height="100px" alt="Rasm"/>
                    </div>
                </div>

                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                    <label class="form-check-label" for="exampleCheck1">Tekshirish</label>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Saqlash</button>
            </div>
        </form>
    </div>
    <!-- /.card -->
@endsection